"""fix models and add alert level

Revision ID: 0dcd0cc44d35
Revises: f12d46b6e3a6
Create Date: 2025-12-02 04:28:15.757026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dcd0cc44d35'
down_revision: Union[str, Sequence[str], None] = 'f12d46b6e3a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vitals', sa.Column('alert_level', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vitals', 'alert_level')
    # ### end Alembic commands ###
