"""add doctor notes table

Revision ID: ab1571903c4e
Revises: 0dcd0cc44d35
Create Date: 2025-12-03 02:00:52.227797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1571903c4e'
down_revision: Union[str, Sequence[str], None] = '0dcd0cc44d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vital_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vital_id'], ['vitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_notes_id'), 'doctor_notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_notes_id'), table_name='doctor_notes')
    op.drop_table('doctor_notes')
    # ### end Alembic commands ###
